### ISSUE TITLE
Upgrade to PostSharp 3

### ISSUE THREAD

**Issue by Pathoschild** [Pathoschild/DesignByContract#5]
Add support for the recent PostSharp 3 release.

**Comment by Pathoschild** [comment]
PostSharp 3 introduces a breaking change affecting aspect serialization, so we can't support both versions of PostSharp without eliminating partial-trust compatibility. PostSharp 3 also seems to be slightly slower than PostSharp 2 so far.

**Comment by georgiosd** [comment]
I guess the only way would be to introduce compiler conditionals where the code is affected and compile two targets from the solution. Then reference the appropriate assembly depending on P# version or have different packages for a while, until P# 2 dies out.

**Comment by georgiosd** [comment]
Sweet - is it any faster?
